---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-client-l5d-config
data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990
    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001
    telemetry:
    - kind: io.l5d.prometheus
    usage:
      enabled: false
    routers:
    - label: egress
      protocol: http
      servers:
      - port: 4140
        ip: 127.0.0.1
      client:
        kind: io.l5d.static
        configs:
        - prefix: /#/io.l5d.k8s/default/http/{service}
          tls:
            commonName: "{service}.default.mesh"
            trustCertsBundle: /etc/secrets/servicemesh-ca.pem
            clientAuth:
              certPath: /etc/secrets/servicemesh.pem
              keyPath: /etc/secrets/servicemesh-key.pem
            protocols:
            - TLSv1.2
      dtab: |
        /svc        => /#/io.l5d.k8s/default/http;
    - label: ingress
      protocol: http
      servers:
      - port: 4141
        ip: 0.0.0.0
        tls:
          caCertPath: /etc/secrets/servicemesh-ca.pem
          certPath: /etc/secrets/servicemesh.pem
          keyPath: /etc/secrets/servicemesh-key.pem
          requireClientAuth: true
          protocols:
          - TLSv1.2
          ciphers:
          - ECDHE-RSA-AES128-GCM-SHA256
      dtab: |
        /svc/echo-client => /$/inet/127.0.0.1/1234