---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-endpoints-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["endpoints", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [ "extensions" ]
  resources: [ "ingresses" ]
  verbs: ["get", "watch", "list"]
